### ISSUE TITLE
Module Error - Please help

### ISSUE THREAD

**Issue by samfakhoury** [LevPasha/Instagram-bot-cs#57]
I successfully installed requests module on mac terminal with pip3 install requests but Im still getting this error !!

Sams-MacBook-Pro:instabot.py-master SamFakhoury$ python example.py
Traceback (most recent call last):
  File "example.py", line 12, in <module>
    from instabot import InstaBot
  File "/Sams Work/FOR SAM 2017/SAMO - Instagram Tools/instabot - Source Codes/instabot - Python Source Codes/instabot.py-master/src/instabot.py", line 15, in <module>
    import requests
ImportError: No module named requests
Sams-MacBook-Pro:instabot.py-master SamFakhoury$

**Comment by samfakhoury** [comment]
I found the solution!  I have 2 versions of Python on my Mac and im using python3.6 so my request should be python3 example.py instead of python example.py - thank you!
